### ISSUE TITLE
Error when installing pyswisseph using pip on python 3.12

### ISSUE THREAD

**Issue by hidp123** [astrorigin/pyswisseph#71]
Hi, getting an error when installing pyswisseph using pip on python 3.12. On 3.11 it installs correctly. So I assume this is the cause of the error. Is there any work around or does the release need an update? Thanks

**Comment by TharakaUmayanga** [comment]
can you paste the error here ?

**Comment by hidp123** [comment]
>>> import subprocess
>>> subprocess.check_call(["python", '-m', 'pip', 'install', 'pyswisseph'])
Collecting pyswisseph
  Downloading pyswisseph-2.10.3.2.tar.gz (6.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 119.7 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyswisseph
  Building wheel for pyswisseph (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyswisseph (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      C:\Users\...\AppData\Local\Temp\pip-build-env-rlcfmrcg\overlay\Lib\site-packages\setuptools\dist.py:314: InformationOnly: Normalizing '2.10.03.2' to '2.10.3.2'
        self.metadata.version = self._normalize_version(self.metadata.version)
      Searching for pkg-config...
      pkg-config not found
      Using internal libswe
      Using internal sqlite3
      running bdist_wheel
      running build
      running build_ext
      building 'swisseph' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyswisseph
Failed to build pyswisseph
ERROR: Could not build wheels for pyswisseph, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'pip', 'install', 'pyswisseph']' returned non-zero exit status 1.

**Comment by TharakaUmayanga** [comment]
I think here's the problem 

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Download MS  C++ Build Tool from here, Restart your pc and try again
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by hidp123** [comment]
On python 3.11 it works, only on 3.12 it gives above error. I'll try what you mentioned.

**Comment by TharakaUmayanga** [comment]
wow.... 6GB is too much.

**Comment by 19karamba** [comment]
+1! On python 3.13 it NOT works,

**Comment by hidp123** [comment]
I have built a .whl file that works, but github won't let me upload it

**Comment by 19karamba** [comment]
hidp123,  Try uploading to https://pypi.org . If it doesn't work out, go to some public file server, and you can place the link here.

**Comment by 19karamba** [comment]
Or create fork,Create a new release, try upload.

**Comment by zkurtz** [comment]
I'm getting a similar error on 3.12 with windows, despite installation of https://visualstudio.microsoft.com/visual-cpp-build-tools/. Might be nice to have documentation of what platforms are supported and/or an updated new release soon.
